export const data = [
	{
		"movie_id" : 1,
		"actors" : "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
		"awards" : "Nominated for 1 Oscar. Another 12 wins & 42 nominations.",
		"boxoffice" : "$389,804,217",
		"country" : "USA",
		"dvd" : "2017-08-22",
		"director" : "James Gunn",
		"genre" : "Action, Adventure, Comedy, Sci-Fi",
		"language" : "English",
		"metascore" : "67",
		"plot" : "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg",
		"production" : "Walt Disney Pictures",
		"rated" : "PG-13",
		"released" : "2017-05-05",
		"response" : "True",
		"runtime" : "136 min",
		"type" : "movie",
		"website" : "https://marvel.com/guardians",
		"writer" : "James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)",
		"year" : "2017",
		"imdb_rating" : "7.7",
		"imdb_votes" : "449,175",
		"imdbid" : "tt3896198",
		"title" : "Guardians of the Galaxy Vol. 2"
	},
	{
		"movie_id" : 2,
		"actors" : "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
		"awards" : "Won 6 Oscars. Another 50 wins & 28 nominations.",
		"boxoffice" : "N/A",
		"country" : "USA",
		"dvd" : "1977-05-25",
		"director" : "George Lucas",
		"genre" : "Action, Adventure, Fantasy, Sci-Fi",
		"language" : "English",
		"metascore" : "90",
		"plot" : "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
		"production" : "20th Century Fox",
		"rated" : "PG",
		"released" : "2004-09-21",
		"response" : "True",
		"runtime" : "121 min",
		"type" : "movie",
		"website" : "http://www.starwars.com/episode-iv/",
		"writer" : "George Lucas",
		"year" : "1977",
		"imdb_rating" : "8.6",
		"imdb_votes" : "1,104,701",
		"imdbid" : "tt0076759",
		"title" : "Star Wars: Episode IV - A New Hope"
	},
	{
		"movie_id" : 3,
		"actors" : "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
		"awards" : "Won 3 Oscars. Another 24 wins & 28 nominations.",
		"boxoffice" : "N/A",
		"country" : "USA",
		"dvd" : "2001-10-09",
		"director" : "Francis Ford Coppola",
		"genre" : "Crime, Drama",
		"language" : "English, Italian, Latin",
		"metascore" : "100",
		"plot" : "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
		"production" : "Paramount Pictures",
		"rated" : "R",
		"released" : "1972-03-24",
		"response" : "True",
		"runtime" : "175 min",
		"type" : "movie",
		"website" : "http://www.thegodfather.com",
		"writer" : "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)",
		"year" : "1977",
		"imdb_rating" : "9.2",
		"imdb_votes" : "1,408,749",
		"imdbid" : "tt0068646",
		"title" : "The Godfather"
    },
    {
		"movie_id" : 1,
		"actors" : "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
		"awards" : "Nominated for 1 Oscar. Another 12 wins & 42 nominations.",
		"boxoffice" : "$389,804,217",
		"country" : "USA",
		"dvd" : "2017-08-22",
		"director" : "James Gunn",
		"genre" : "Action, Adventure, Comedy, Sci-Fi",
		"language" : "English",
		"metascore" : "67",
		"plot" : "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg",
		"production" : "Walt Disney Pictures",
		"rated" : "PG-13",
		"released" : "2017-05-05",
		"response" : "True",
		"runtime" : "136 min",
		"type" : "movie",
		"website" : "https://marvel.com/guardians",
		"writer" : "James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)",
		"year" : "2017",
		"imdb_rating" : "7.7",
		"imdb_votes" : "449,175",
		"imdbid" : "tt3896198",
		"title" : "Guardians of the Galaxy Vol. 2"
	},
	{
		"movie_id" : 2,
		"actors" : "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
		"awards" : "Won 6 Oscars. Another 50 wins & 28 nominations.",
		"boxoffice" : "N/A",
		"country" : "USA",
		"dvd" : "1977-05-25",
		"director" : "George Lucas",
		"genre" : "Action, Adventure, Fantasy, Sci-Fi",
		"language" : "English",
		"metascore" : "90",
		"plot" : "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
		"production" : "20th Century Fox",
		"rated" : "PG",
		"released" : "2004-09-21",
		"response" : "True",
		"runtime" : "121 min",
		"type" : "movie",
		"website" : "http://www.starwars.com/episode-iv/",
		"writer" : "George Lucas",
		"year" : "1977",
		"imdb_rating" : "8.6",
		"imdb_votes" : "1,104,701",
		"imdbid" : "tt0076759",
		"title" : "Star Wars: Episode IV - A New Hope"
	},
	{
		"movie_id" : 3,
		"actors" : "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
		"awards" : "Won 3 Oscars. Another 24 wins & 28 nominations.",
		"boxoffice" : "N/A",
		"country" : "USA",
		"dvd" : "2001-10-09",
		"director" : "Francis Ford Coppola",
		"genre" : "Crime, Drama",
		"language" : "English, Italian, Latin",
		"metascore" : "100",
		"plot" : "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
		"poster" : "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
		"production" : "Paramount Pictures",
		"rated" : "R",
		"released" : "1972-03-24",
		"response" : "True",
		"runtime" : "175 min",
		"type" : "movie",
		"website" : "http://www.thegodfather.com",
		"writer" : "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)",
		"year" : "1977",
		"imdb_rating" : "9.2",
		"imdb_votes" : "1,408,749",
		"imdbid" : "tt0068646",
		"title" : "The Godfather"
	}
]


